name: "encoder"
backend: "python"
max_batch_size: 64

parameters [
  {
    key: "vocabulary",
    value: {
      string_value: "./model_repo_paraformer_torchscritpts/feature_extractor/config.yaml"
    }
  },
  {
    key: "model_path"
    value: {
      string_value: "./model_repo_paraformer_torchscritpts/encoder/1/model.torchscripts"
    }
  },
  {
    key: "FORCE_CPU_ONLY_INPUT_TENSORS" 
    value: {
      string_value: "no"
    }
  }
]

input [
  {
    name: "speech"
    data_type: TYPE_FP32
    dims: [-1, 560]
  },
  {
    name: "speech_lengths"
    data_type: TYPE_INT32
    dims: [-1]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

dynamic_batching {
  preferred_batch_size: [2, 4, 8, 16, 64]
  max_queue_delay_microseconds: 500
}

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]
