map $uri $funasr_conversion_target {
    default "";
    /go/github https://github.com/modelscope/FunASR;
    /go/fun-asr https://github.com/QwenAudio/Fun-ASR;
    /go/sensevoice https://github.com/QwenAudio/SenseVoice;
    /go/funclip https://github.com/modelscope/FunClip;
    /go/docs https://github.com/modelscope/FunASR/tree/main/docs;
    /go/releases https://github.com/modelscope/FunASR/releases;
    /go/deploy-vllm https://www.funasr.com/deploy/vllm.html;
    /go/deploy-llama-cpp https://www.funasr.com/deploy/llama-cpp.html;
}
